# Generate well-level bulk profiles profiles

NOTE: We are normalizing the bulk-profile plates to the negative controls as the "standard".

## Import libraries

In [1]:
import os
import pathlib
import pprint

import pandas as pd

from pycytominer import aggregate, annotate, normalize, feature_select
from pycytominer.cyto_utils import infer_cp_features

## Set paths and variables

In [2]:
# get the batch to process from environment variable
batch_to_process = os.environ.get("BATCH", "batch_1")
if batch_to_process is None:
    raise ValueError(
        "Please set the BATCH environment variable before running this script."
    )

# base directory where batches are located
base_dir = pathlib.Path("./data/").resolve(strict=True)

# Decide what to process
if batch_to_process:
    print(f"Processing {batch_to_process}")
    batch_dirs = [base_dir / batch_to_process]
else:
    print("No specific batch set, processing all available batches")
    batch_dirs = [p for p in base_dir.glob("batch_*") if p.is_dir()]

# path for platemap directory
platemap_dir = pathlib.Path("../metadata/updated_platemaps/")

# Load the barcode_platemap file
barcode_platemap_df = pd.read_csv(
    (platemap_dir / "updated_barcode_platemap.csv").resolve()
)

# operations to perform for feature selection
feature_select_ops = [
    "variance_threshold",
    "correlation_threshold",
    "blocklist",
    "drop_na_columns",
]

Processing batch_1

## Set dictionary with plates to process

In [3]:
plate_info_dictionary = {}

# Loop over batches and layouts
for batch_dir in batch_dirs:
    layouts = [p for p in batch_dir.iterdir() if p.is_dir()]  # all layouts
    for layout_dir in layouts:
        qc_labeled_dir = layout_dir / "qc_labeled_profiles"
        output_dir = layout_dir / "bulk_profiles"
        output_dir.mkdir(parents=True, exist_ok=True)

        # add spherize dir to dictionary
        spherize_dir = layout_dir / "spherized_bulk_profiles"
        spherize_dir.mkdir(parents=True, exist_ok=True)

        # Extract plate names from parquet files
        parquet_files = list(qc_labeled_dir.glob("*.parquet"))
        plate_names = [
            "_".join(f.stem.split("_")[:2]) if len(f.stem.split("_")) >= 2 else f.stem
            for f in parquet_files
        ]

        for name in plate_names:
            # Find the corresponding parquet file
            matching_files = [f for f in parquet_files if name in f.stem]
            if not matching_files:
                continue
            profile_path = matching_files[0].resolve(strict=True)

            # Find corresponding platemap CSV
            platemap_row = barcode_platemap_df.loc[
                barcode_platemap_df["plate_barcode"] == name
            ]
            if platemap_row.empty:
                raise ValueError(f"No platemap found for plate {name}")
            platemap_path = (
                platemap_dir / f"{platemap_row['platemap_file'].values[0]}.csv"
            ).resolve(strict=True)

            # Add to dictionary
            plate_info_dictionary[name] = {
                "profile_path": profile_path,
                "platemap_path": platemap_path,
                "output_dir": output_dir,
                "spherize_output_dir": spherize_dir,
            }

# View dictionary
print("Number of plates to process:", len(plate_info_dictionary))
pprint.pprint(plate_info_dictionary, indent=4)

Number of plates to process: 16
{   'CARD-CelIns-CX7_251023210001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251023210001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251124150001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251124150001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251125110001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251125110001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251126130001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251126130001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251130110002': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251130110002_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251201110001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251201110001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251201190001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251201190001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251202100001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251202100001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251203170001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251203170001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251205100001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251205100001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251208160001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251208160001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251210180001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251210180001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251211180001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251211180001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251212100001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251212100001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251212180001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251212180001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/spherized_bulk_profiles')},
    'CARD-CelIns-CX7_251213150001': {   'output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/erikserrano/mnt/bandicoot/CFReT_screening_data/screen_profiles/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251213150001_qc_labeled.parquet'),
                                        'spherize_output_dir': PosixPath('/home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/spherized_bulk_profiles')}}

## Process data with pycytominer

In [ ]:
for plate, info in plate_info_dictionary.items():
    output_dir = info["output_dir"]
    print("Performing preprocessing on", plate, output_dir)

    # Use the output_dir from the dictionary for this specific plate
    output_dir = info["output_dir"]
    spherized_output_dir = info["spherize_output_dir"]

    # generating all output file paths using the output_dir from the dictionary
    output_annotated_file = str(output_dir / f"{plate}_bulk_annotated.parquet")
    output_normalized_file = str(output_dir / f"{plate}_bulk_normalized.parquet")
    output_feature_select_file = str(
        output_dir / f"{plate}_bulk_feature_selected.parquet"
    )
    output_spherized_file = str(
        spherized_output_dir / f"{plate}_bulk_spherized.parquet"
    )

    profile_df = pd.read_parquet(info["profile_path"])
    platemap_df = pd.read_csv(info["platemap_path"])

    # Drop all rows in the profiles that failed any Metadata_cqc columns
    cqc_columns = [col for col in profile_df.columns if col.startswith("Metadata_cqc")]
    if cqc_columns:
        profile_df = profile_df[~profile_df[cqc_columns].any(axis=1)]

    # Step 1: Aggregate single-cell data to the well-level using the median
    print("Performing aggregation for", plate, "...")
    aggregated_df = aggregate(
        population_df=profile_df,
        operation="median",
        strata=["Image_Metadata_Plate", "Image_Metadata_Well"],
    )

    print("Performing annotation for", plate, "...")
    # Step 2: Annotation
    annotate(
        profiles=aggregated_df,
        platemap=platemap_df,
        join_on=["Metadata_well_position", "Image_Metadata_Well"],
        output_file=output_annotated_file,
        output_type="parquet",
    )

    # Load the annotated parquet file to fix metadata columns names
    annotated_df = pd.read_parquet(output_annotated_file)

    # Rename columns
    annotated_df.rename(columns={"Image_Metadata_Site": "Metadata_Site"}, inplace=True)

    # Save back
    annotated_df.to_parquet(output_annotated_file, index=False)

    # Step 2: Normalization
    print("Performing normalization for", plate, "...")
    neg_control_query = "Metadata_treatment == 'DMSO' and Metadata_cell_type == 'failing'"
    normalized_df = normalize(
        profiles=output_annotated_file,
        method="standardize",
        output_file=output_normalized_file,
        output_type="parquet",
        samples=neg_control_query,
    )

    # Step 3: Feature selection
    print("Performing feature selection for", plate, "...")
    global_fs_df = feature_select(
        profiles=normalized_df,
        operation=feature_select_ops,
        na_cutoff=0,
        output_type="parquet",
        blocklist_file="./blocklist_features.txt",
        corr_threshold=0.95,
        freq_cut=0.05,
    )

    print(
        f"Aggregation, annotation, normalization, and feature selection complete for {plate}"
    )

    # step 4: spherize profiles
    print("Performing spherization for", plate, "...")
    
    # Apply feature selection to the negative control samples only to remove 
    # low-to-zero variance features
    neg_control_fs_df = feature_select(
        profiles=global_fs_df,
        operation=["variance_threshold", "blocklist"],
        freq_cut=0.05,
        unique_cut=0.01,
        samples=neg_control_query,
        blocklist_file="./blocklist_features.txt",
    )

    # Update the global feature-selected dataframe to only include the features 
    # retained after filtering the negative controls for low-to-zero variance.
    retained_cols = [col for col in global_fs_df.columns if col in neg_control_fs_df.columns]
    global_fs_df = global_fs_df[retained_cols]

    # Save the final feature-selected profiles
    global_fs_df.to_parquet(output_feature_select_file, index=False)

    # Spherize using the negative controls as the reference population
    normalize(
        profiles=global_fs_df,
        method="spherize",
        output_file=output_spherized_file,
        output_type="parquet",
        samples=neg_control_query,
        spherize_center=True,
        spherize_method="ZCA-cor",
        spherize_epsilon=1e-6,
    )

Performing preprocessing on CARD-CelIns-CX7_251205100001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251205100001 ...
Performing annotation for CARD-CelIns-CX7_251205100001 ...
Performing normalization for CARD-CelIns-CX7_251205100001 ...
Performing feature selection for CARD-CelIns-CX7_251205100001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251205100001
Performing spherization for CARD-CelIns-CX7_251205100001 ...
Performing preprocessing on CARD-CelIns-CX7_251210180001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251210180001 ...
Performing annotation for CARD-CelIns-CX7_251210180001 ...
Performing normalization for CARD-CelIns-CX7_251210180001 ...
Performing feature selection for CARD-CelIns-CX7_251210180001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251210180001
Performing spherization for CARD-CelIns-CX7_251210180001 ...
Performing preprocessing on CARD-CelIns-CX7_251203170001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251203170001 ...
Performing annotation for CARD-CelIns-CX7_251203170001 ...
Performing normalization for CARD-CelIns-CX7_251203170001 ...
Performing feature selection for CARD-CelIns-CX7_251203170001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251203170001
Performing spherization for CARD-CelIns-CX7_251203170001 ...
Performing preprocessing on CARD-CelIns-CX7_251208160001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251208160001 ...
Performing annotation for CARD-CelIns-CX7_251208160001 ...
Performing normalization for CARD-CelIns-CX7_251208160001 ...
Performing feature selection for CARD-CelIns-CX7_251208160001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251208160001
Performing spherization for CARD-CelIns-CX7_251208160001 ...
Performing preprocessing on CARD-CelIns-CX7_251212180001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251212180001 ...
Performing annotation for CARD-CelIns-CX7_251212180001 ...
Performing normalization for CARD-CelIns-CX7_251212180001 ...
Performing feature selection for CARD-CelIns-CX7_251212180001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251212180001
Performing spherization for CARD-CelIns-CX7_251212180001 ...
Performing preprocessing on CARD-CelIns-CX7_251211180001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251211180001 ...
Performing annotation for CARD-CelIns-CX7_251211180001 ...
Performing normalization for CARD-CelIns-CX7_251211180001 ...
Performing feature selection for CARD-CelIns-CX7_251211180001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251211180001
Performing spherization for CARD-CelIns-CX7_251211180001 ...
Performing preprocessing on CARD-CelIns-CX7_251213150001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251213150001 ...
Performing annotation for CARD-CelIns-CX7_251213150001 ...
Performing normalization for CARD-CelIns-CX7_251213150001 ...
Performing feature selection for CARD-CelIns-CX7_251213150001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251213150001
Performing spherization for CARD-CelIns-CX7_251213150001 ...
Performing preprocessing on CARD-CelIns-CX7_251212100001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251212100001 ...
Performing annotation for CARD-CelIns-CX7_251212100001 ...
Performing normalization for CARD-CelIns-CX7_251212100001 ...
Performing feature selection for CARD-CelIns-CX7_251212100001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251212100001
Performing spherization for CARD-CelIns-CX7_251212100001 ...
Performing preprocessing on CARD-CelIns-CX7_251201110001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251201110001 ...
Performing annotation for CARD-CelIns-CX7_251201110001 ...
Performing normalization for CARD-CelIns-CX7_251201110001 ...
Performing feature selection for CARD-CelIns-CX7_251201110001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251201110001
Performing spherization for CARD-CelIns-CX7_251201110001 ...
Performing preprocessing on CARD-CelIns-CX7_251130110002 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251130110002 ...
Performing annotation for CARD-CelIns-CX7_251130110002 ...
Performing normalization for CARD-CelIns-CX7_251130110002 ...
Performing feature selection for CARD-CelIns-CX7_251130110002 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251130110002
Performing spherization for CARD-CelIns-CX7_251130110002 ...
Performing preprocessing on CARD-CelIns-CX7_251202100001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251202100001 ...
Performing annotation for CARD-CelIns-CX7_251202100001 ...
Performing normalization for CARD-CelIns-CX7_251202100001 ...
Performing feature selection for CARD-CelIns-CX7_251202100001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251202100001
Performing spherization for CARD-CelIns-CX7_251202100001 ...
Performing preprocessing on CARD-CelIns-CX7_251201190001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251201190001 ...
Performing annotation for CARD-CelIns-CX7_251201190001 ...
Performing normalization for CARD-CelIns-CX7_251201190001 ...
Performing feature selection for CARD-CelIns-CX7_251201190001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251201190001
Performing spherization for CARD-CelIns-CX7_251201190001 ...
Performing preprocessing on CARD-CelIns-CX7_251125110001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251125110001 ...
Performing annotation for CARD-CelIns-CX7_251125110001 ...
Performing normalization for CARD-CelIns-CX7_251125110001 ...
Performing feature selection for CARD-CelIns-CX7_251125110001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251125110001
Performing spherization for CARD-CelIns-CX7_251125110001 ...
Performing preprocessing on CARD-CelIns-CX7_251126130001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251126130001 ...
Performing annotation for CARD-CelIns-CX7_251126130001 ...
Performing normalization for CARD-CelIns-CX7_251126130001 ...
Performing feature selection for CARD-CelIns-CX7_251126130001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251126130001
Performing spherization for CARD-CelIns-CX7_251126130001 ...
Performing preprocessing on CARD-CelIns-CX7_251023210001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251023210001 ...
Performing annotation for CARD-CelIns-CX7_251023210001 ...
Performing normalization for CARD-CelIns-CX7_251023210001 ...
Performing feature selection for CARD-CelIns-CX7_251023210001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251023210001
Performing spherization for CARD-CelIns-CX7_251023210001 ...
Performing preprocessing on CARD-CelIns-CX7_251124150001 /home/erikserrano/Projects/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251124150001 ...
Performing annotation for CARD-CelIns-CX7_251124150001 ...
Performing normalization for CARD-CelIns-CX7_251124150001 ...
Performing feature selection for CARD-CelIns-CX7_251124150001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251124150001
Performing spherization for CARD-CelIns-CX7_251124150001 ...

In [5]:
# Check output file
test_df = pd.read_parquet(output_feature_select_file)

print(test_df.shape)
print("Plate:", test_df.Metadata_Plate.unique())
print(
    "Metadata columns:", [col for col in test_df.columns if col.startswith("Metadata_")]
)
test_df.head(2)

(53, 869)
Plate: ['CARD-CelIns-CX7_251124150001']
Metadata columns: ['Metadata_WellRow', 'Metadata_WellCol', 'Metadata_heart_number', 'Metadata_cell_type', 'Metadata_heart_failure_type', 'Metadata_treatment', 'Metadata_Pathway', 'Metadata_Plate', 'Metadata_Well']

,Metadata_WellRow,Metadata_WellCol,Metadata_heart_number,Metadata_cell_type,Metadata_heart_failure_type,Metadata_treatment,Metadata_Pathway,Metadata_Plate,Metadata_Well,Cytoplasm_AreaShape_BoundingBoxMaximum_X,...,Nuclei_Texture_InfoMeas2_Actin_3_03_256,Nuclei_Texture_InfoMeas2_DNA_3_00_256,Nuclei_Texture_InfoMeas2_DNA_3_02_256,Nuclei_Texture_InfoMeas2_Mito_3_00_256,Nuclei_Texture_InverseDifferenceMoment_DNA_3_00_256,Nuclei_Texture_InverseDifferenceMoment_ER_3_02_256,Nuclei_Texture_InverseDifferenceMoment_Mito_3_00_256,Nuclei_Texture_InverseDifferenceMoment_PM_3_01_256,Nuclei_Texture_SumVariance_Actin_3_01_256,Nuclei_Texture_SumVariance_Mito_3_00_256
0,B,2,7,healthy,None,DMSO,None,CARD-CelIns-CX7_251124150001,B02,1.652205,...,-6.380152,2.387172,1.650850,0.961068,-0.790400,-2.766074,0.729521,-2.912732,-2.192819,-0.049205
1,B,3,25,failing,dilated_cardiomyopathy,UCD-0159256,Apoptosis,CARD-CelIns-CX7_251124150001,B03,0.527299,...,1.376377,0.668726,0.692385,0.120936,2.325411,1.588030,-0.515336,-3.439496,2.423953,1.432375

In [6]:
# Check output file
test_df = pd.read_parquet(output_annotated_file)

print(test_df.shape)
print("Plate:", test_df.Metadata_Plate.unique())
print(
    "Metadata columns:", [col for col in test_df.columns if col.startswith("Metadata_")]
)
test_df.head(2)

(53, 2462)
Plate: ['CARD-CelIns-CX7_251124150001']
Metadata columns: ['Metadata_WellRow', 'Metadata_WellCol', 'Metadata_heart_number', 'Metadata_cell_type', 'Metadata_heart_failure_type', 'Metadata_treatment', 'Metadata_Pathway', 'Metadata_Plate', 'Metadata_Well']

,Metadata_WellRow,Metadata_WellCol,Metadata_heart_number,Metadata_cell_type,Metadata_heart_failure_type,Metadata_treatment,Metadata_Pathway,Metadata_Plate,Metadata_Well,Cytoplasm_AreaShape_Area,...,Nuclei_Texture_Variance_ER_3_02_256,Nuclei_Texture_Variance_ER_3_03_256,Nuclei_Texture_Variance_Mito_3_00_256,Nuclei_Texture_Variance_Mito_3_01_256,Nuclei_Texture_Variance_Mito_3_02_256,Nuclei_Texture_Variance_Mito_3_03_256,Nuclei_Texture_Variance_PM_3_00_256,Nuclei_Texture_Variance_PM_3_01_256,Nuclei_Texture_Variance_PM_3_02_256,Nuclei_Texture_Variance_PM_3_03_256
0,B,2,7,healthy,None,DMSO,None,CARD-CelIns-CX7_251124150001,B02,30709.0,...,4.699879,4.522241,1.974404,1.842319,2.039690,1.948798,4.386677,4.362827,4.372789,4.310573
1,B,3,25,failing,dilated_cardiomyopathy,UCD-0159256,Apoptosis,CARD-CelIns-CX7_251124150001,B03,32597.0,...,4.206517,4.065663,2.791381,2.550746,2.626612,2.521797,4.758848,4.645544,4.722644,4.691256

In [7]:
# check spherized output file
test_df = pd.read_parquet(output_spherized_file)

print(test_df.shape)
print("Plate:", test_df.Metadata_Plate.unique())
print(
    "Metadata columns:", [col for col in test_df.columns if col.startswith("Metadata_")]
)
test_df.head(2)

(53, 869)
Plate: ['CARD-CelIns-CX7_251124150001']
Metadata columns: ['Metadata_WellRow', 'Metadata_WellCol', 'Metadata_heart_number', 'Metadata_cell_type', 'Metadata_heart_failure_type', 'Metadata_treatment', 'Metadata_Pathway', 'Metadata_Plate', 'Metadata_Well']

,Metadata_WellRow,Metadata_WellCol,Metadata_heart_number,Metadata_cell_type,Metadata_heart_failure_type,Metadata_treatment,Metadata_Pathway,Metadata_Plate,Metadata_Well,Cytoplasm_AreaShape_BoundingBoxMaximum_X,...,Nuclei_Texture_InfoMeas2_Actin_3_03_256,Nuclei_Texture_InfoMeas2_DNA_3_00_256,Nuclei_Texture_InfoMeas2_DNA_3_02_256,Nuclei_Texture_InfoMeas2_Mito_3_00_256,Nuclei_Texture_InverseDifferenceMoment_DNA_3_00_256,Nuclei_Texture_InverseDifferenceMoment_ER_3_02_256,Nuclei_Texture_InverseDifferenceMoment_Mito_3_00_256,Nuclei_Texture_InverseDifferenceMoment_PM_3_01_256,Nuclei_Texture_SumVariance_Actin_3_01_256,Nuclei_Texture_SumVariance_Mito_3_00_256
0,B,2,7,healthy,None,DMSO,None,CARD-CelIns-CX7_251124150001,B02,0.100388,...,-0.351374,0.129179,0.084437,0.043421,-0.039939,-0.158533,0.052704,-0.161766,-0.115539,-0.012893
1,B,3,25,failing,dilated_cardiomyopathy,UCD-0159256,Apoptosis,CARD-CelIns-CX7_251124150001,B03,0.021202,...,0.068453,0.037166,0.040544,0.012021,0.129413,0.096084,-0.035687,-0.194027,0.127479,0.084926