# Generate well-level bulk profiles profiles

NOTE: We are normalizing the bulk-profile plates to the negative controls as the "standard".

## Import libraries

In [ ]:
import os
import pathlib
import pprint

import pandas as pd

from pycytominer import aggregate, annotate, normalize, feature_select

## Set paths and variables

In [ ]:
# get the batch to process from environment variable
batch_to_process = os.environ.get("BATCH", "batch_1")
if batch_to_process is None:
    raise ValueError(
        "Please set the BATCH environment variable before running this script."
    )

# base directory where batches are located
base_dir = pathlib.Path("./data/").resolve(strict=True)

# Decide what to process
if batch_to_process:
    print(f"Processing {batch_to_process}")
    batch_dirs = [base_dir / batch_to_process]
else:
    print("No specific batch set, processing all available batches")
    batch_dirs = [p for p in base_dir.glob("batch_*") if p.is_dir()]

# path for platemap directory
platemap_dir = pathlib.Path("../metadata/updated_platemaps/")

# Load the barcode_platemap file
barcode_platemap_df = pd.read_csv(
    (platemap_dir / "updated_barcode_platemap.csv").resolve()
)

# operations to perform for feature selection
feature_select_ops = [
    "variance_threshold",
    "correlation_threshold",
    "blocklist",
    "drop_na_columns",
]

## Set dictionary with plates to process

In [ ]:
plate_info_dictionary = {}

# Loop over batches and layouts
for batch_dir in batch_dirs:
    layouts = [p for p in batch_dir.iterdir() if p.is_dir()]  # all layouts
    for layout_dir in layouts:
        qc_labeled_dir = layout_dir / "qc_labeled_profiles"
        output_dir = layout_dir / "bulk_profiles"
        output_dir.mkdir(parents=True, exist_ok=True)

        # Extract plate names from parquet files
        parquet_files = list(qc_labeled_dir.glob("*.parquet"))
        plate_names = [
            "_".join(f.stem.split("_")[:2]) if len(f.stem.split("_")) >= 2 else f.stem
            for f in parquet_files
        ]

        for name in plate_names:
            # Find the corresponding parquet file
            matching_files = [f for f in parquet_files if name in f.stem]
            if not matching_files:
                continue
            profile_path = matching_files[0].resolve(strict=True)

            # Find corresponding platemap CSV
            platemap_row = barcode_platemap_df.loc[
                barcode_platemap_df["plate_barcode"] == name
            ]
            if platemap_row.empty:
                raise ValueError(f"No platemap found for plate {name}")
            platemap_path = (
                platemap_dir / f"{platemap_row['platemap_file'].values[0]}.csv"
            ).resolve(strict=True)

            # Add to dictionary
            plate_info_dictionary[name] = {
                "profile_path": profile_path,
                "platemap_path": platemap_path,
                "output_dir": output_dir,
            }

# View dictionary
print("Number of plates to process:", len(plate_info_dictionary))
pprint.pprint(plate_info_dictionary, indent=4)

Number of plates to process: 16
{   'CARD-CelIns-CX7_251023210001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251023210001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251124150001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251124150001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251125110001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251125110001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251126130001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_1_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/qc_labeled_profiles/CARD-CelIns-CX7_251126130001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251130110002': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251130110002_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251201110001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251201110001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251201190001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251201190001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251202100001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_2_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/qc_labeled_profiles/CARD-CelIns-CX7_251202100001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251203170001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251203170001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251205100001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251205100001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251208160001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251208160001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251210180001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_3_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/qc_labeled_profiles/CARD-CelIns-CX7_251210180001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251211180001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251211180001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251212100001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251212100001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251212180001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251212180001_qc_labeled.parquet')},
    'CARD-CelIns-CX7_251213150001': {   'output_dir': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles'),
                                        'platemap_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/metadata/updated_platemaps/Target_Selective_Library_Screen_Plate_4_with_pathways.csv'),
                                        'profile_path': PosixPath('/home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/qc_labeled_profiles/CARD-CelIns-CX7_251213150001_qc_labeled.parquet')}}

## Process data with pycytominer

In [ ]:
for plate, info in plate_info_dictionary.items():
    output_dir = info["output_dir"]
    print("Performing preprocessing on", plate, output_dir)

    # Use the output_dir from the dictionary for this specific plate
    output_dir = info["output_dir"]
    output_dir.mkdir(parents=True, exist_ok=True)

    output_annotated_file = str(output_dir / f"{plate}_bulk_annotated.parquet")
    output_normalized_file = str(output_dir / f"{plate}_bulk_normalized.parquet")
    output_feature_select_file = str(
        output_dir / f"{plate}_bulk_feature_selected.parquet"
    )

    profile_df = pd.read_parquet(info["profile_path"])
    platemap_df = pd.read_csv(info["platemap_path"])

    # Drop all rows in the profiles that failed any Metadata_cqc columns
    cqc_columns = [col for col in profile_df.columns if col.startswith("Metadata_cqc")]
    if cqc_columns:
        profile_df = profile_df[~profile_df[cqc_columns].any(axis=1)]

    # Step 1: Aggregate single-cell data to the well-level using the median
    print("Performing aggregation for", plate, "...")
    aggregated_df = aggregate(
        population_df=profile_df,
        operation="median",
        strata=["Image_Metadata_Plate", "Image_Metadata_Well"],
    )

    print("Performing annotation for", plate, "...")
    # Step 2: Annotation
    annotate(
        profiles=aggregated_df,
        platemap=platemap_df,
        join_on=["Metadata_well_position", "Image_Metadata_Well"],
        output_file=output_annotated_file,
        output_type="parquet",
    )

    # Load the annotated parquet file to fix metadata columns names
    annotated_df = pd.read_parquet(output_annotated_file)

    # Rename columns
    annotated_df.rename(columns={"Image_Metadata_Site": "Metadata_Site"}, inplace=True)

    # Save back
    annotated_df.to_parquet(output_annotated_file, index=False)

    # Step 2: Normalization
    print("Performing feature selection for", plate, "...")
    normalized_df = normalize(
        profiles=output_annotated_file,
        method="standardize",
        output_file=output_normalized_file,
        output_type="parquet",
        samples="Metadata_treatment == 'DMSO' and Metadata_cell_type == 'failing'",
    )

    # Step 3: Feature selection
    print("Performing feature selection for", plate, "...")
    feature_select(
        profiles=normalized_df,
        operation=feature_select_ops,
        na_cutoff=0,
        output_file=output_feature_select_file,
        output_type="parquet",
        blocklist_file="./blocklist_features.txt",
    )

    print(
        f"Aggregation, annotation, normalization, and feature selection complete for {plate}"
    )

Performing preprocessing on CARD-CelIns-CX7_251203170001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251203170001 ...
Performing annotation for CARD-CelIns-CX7_251203170001 ...
Performing feature selection for CARD-CelIns-CX7_251203170001 ...
Performing feature selection for CARD-CelIns-CX7_251203170001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251203170001
Performing preprocessing on CARD-CelIns-CX7_251208160001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251208160001 ...
Performing annotation for CARD-CelIns-CX7_251208160001 ...
Performing feature selection for CARD-CelIns-CX7_251208160001 ...
Performing feature selection for CARD-CelIns-CX7_251208160001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251208160001
Performing preprocessing on CARD-CelIns-CX7_251205100001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251205100001 ...
Performing annotation for CARD-CelIns-CX7_251205100001 ...
Performing feature selection for CARD-CelIns-CX7_251205100001 ...
Performing feature selection for CARD-CelIns-CX7_251205100001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251205100001
Performing preprocessing on CARD-CelIns-CX7_251210180001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_3/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251210180001 ...
Performing annotation for CARD-CelIns-CX7_251210180001 ...
Performing feature selection for CARD-CelIns-CX7_251210180001 ...
Performing feature selection for CARD-CelIns-CX7_251210180001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251210180001
Performing preprocessing on CARD-CelIns-CX7_251212100001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251212100001 ...
Performing annotation for CARD-CelIns-CX7_251212100001 ...
Performing feature selection for CARD-CelIns-CX7_251212100001 ...
Performing feature selection for CARD-CelIns-CX7_251212100001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251212100001
Performing preprocessing on CARD-CelIns-CX7_251213150001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251213150001 ...
Performing annotation for CARD-CelIns-CX7_251213150001 ...
Performing feature selection for CARD-CelIns-CX7_251213150001 ...
Performing feature selection for CARD-CelIns-CX7_251213150001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251213150001
Performing preprocessing on CARD-CelIns-CX7_251212180001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251212180001 ...
Performing annotation for CARD-CelIns-CX7_251212180001 ...
Performing feature selection for CARD-CelIns-CX7_251212180001 ...
Performing feature selection for CARD-CelIns-CX7_251212180001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251212180001
Performing preprocessing on CARD-CelIns-CX7_251211180001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_4/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251211180001 ...
Performing annotation for CARD-CelIns-CX7_251211180001 ...
Performing feature selection for CARD-CelIns-CX7_251211180001 ...
Performing feature selection for CARD-CelIns-CX7_251211180001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251211180001
Performing preprocessing on CARD-CelIns-CX7_251124150001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251124150001 ...
Performing annotation for CARD-CelIns-CX7_251124150001 ...
Performing feature selection for CARD-CelIns-CX7_251124150001 ...
Performing feature selection for CARD-CelIns-CX7_251124150001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251124150001
Performing preprocessing on CARD-CelIns-CX7_251023210001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251023210001 ...
Performing annotation for CARD-CelIns-CX7_251023210001 ...
Performing feature selection for CARD-CelIns-CX7_251023210001 ...
Performing feature selection for CARD-CelIns-CX7_251023210001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251023210001
Performing preprocessing on CARD-CelIns-CX7_251126130001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251126130001 ...
Performing annotation for CARD-CelIns-CX7_251126130001 ...
Performing feature selection for CARD-CelIns-CX7_251126130001 ...
Performing feature selection for CARD-CelIns-CX7_251126130001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251126130001
Performing preprocessing on CARD-CelIns-CX7_251125110001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_1/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251125110001 ...
Performing annotation for CARD-CelIns-CX7_251125110001 ...
Performing feature selection for CARD-CelIns-CX7_251125110001 ...
Performing feature selection for CARD-CelIns-CX7_251125110001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251125110001
Performing preprocessing on CARD-CelIns-CX7_251201110001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251201110001 ...
Performing annotation for CARD-CelIns-CX7_251201110001 ...
Performing feature selection for CARD-CelIns-CX7_251201110001 ...
Performing feature selection for CARD-CelIns-CX7_251201110001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251201110001
Performing preprocessing on CARD-CelIns-CX7_251202100001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251202100001 ...
Performing annotation for CARD-CelIns-CX7_251202100001 ...
Performing feature selection for CARD-CelIns-CX7_251202100001 ...
Performing feature selection for CARD-CelIns-CX7_251202100001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251202100001
Performing preprocessing on CARD-CelIns-CX7_251130110002 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251130110002 ...
Performing annotation for CARD-CelIns-CX7_251130110002 ...
Performing feature selection for CARD-CelIns-CX7_251130110002 ...
Performing feature selection for CARD-CelIns-CX7_251130110002 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251130110002
Performing preprocessing on CARD-CelIns-CX7_251201190001 /home/jenna/targeted_fibrosis_drug_screen/3.preprocessing_features/data/batch_1/platemap_2/bulk_profiles
Performing aggregation for CARD-CelIns-CX7_251201190001 ...
Performing annotation for CARD-CelIns-CX7_251201190001 ...
Performing feature selection for CARD-CelIns-CX7_251201190001 ...
Performing feature selection for CARD-CelIns-CX7_251201190001 ...
Aggregation, annotation, normalization, and feature selection complete for CARD-CelIns-CX7_251201190001

In [ ]:
# Check output file
test_df = pd.read_parquet(output_feature_select_file)

print(test_df.shape)
print("Plate:", test_df.Metadata_Plate.unique())
print(
    "Metadata columns:", [col for col in test_df.columns if col.startswith("Metadata_")]
)
test_df.head(2)

(49, 497)
Plate: ['CARD-CelIns-CX7_251201190001']
Metadata columns: ['Metadata_WellRow', 'Metadata_WellCol', 'Metadata_heart_number', 'Metadata_cell_type', 'Metadata_heart_failure_type', 'Metadata_treatment', 'Metadata_Pathway', 'Metadata_Plate', 'Metadata_Well']

,Metadata_WellRow,Metadata_WellCol,Metadata_heart_number,Metadata_cell_type,Metadata_heart_failure_type,Metadata_treatment,Metadata_Pathway,Metadata_Plate,Metadata_Well,Cytoplasm_AreaShape_BoundingBoxMaximum_X,...,Nuclei_Texture_InfoMeas1_DNA_3_02_256,Nuclei_Texture_InfoMeas1_ER_3_00_256,Nuclei_Texture_InfoMeas1_ER_3_02_256,Nuclei_Texture_InfoMeas1_Mito_3_02_256,Nuclei_Texture_InfoMeas1_PM_3_02_256,Nuclei_Texture_InfoMeas2_DNA_3_02_256,Nuclei_Texture_InfoMeas2_Mito_3_02_256,Nuclei_Texture_InverseDifferenceMoment_Actin_3_00_256,Nuclei_Texture_InverseDifferenceMoment_DNA_3_01_256,Nuclei_Texture_InverseDifferenceMoment_Mito_3_01_256
0,B,2,7,healthy,None,DMSO,None,CARD-CelIns-CX7_251201190001,B02,0.470073,...,-1.792388,-1.391521,-1.499551,-3.943339,-3.544708,3.172974,3.747022,1.278618,-3.830359,-2.816754
1,B,3,25,failing,dilated_cardiomyopathy,UCD-0159266,Others,CARD-CelIns-CX7_251201190001,B03,0.347446,...,0.692941,1.083713,1.290209,0.818508,0.273418,-0.483481,-1.574973,-5.464754,-0.783483,1.332271

In [6]:
# Check output file
test_df = pd.read_parquet(output_annotated_file)

print(test_df.shape)
print("Plate:", test_df.Metadata_Plate.unique())
print(
    "Metadata columns:", [col for col in test_df.columns if col.startswith("Metadata_")]
)
test_df.head(2)

(49, 2462)
Plate: ['CARD-CelIns-CX7_251201190001']
Metadata columns: ['Metadata_WellRow', 'Metadata_WellCol', 'Metadata_heart_number', 'Metadata_cell_type', 'Metadata_heart_failure_type', 'Metadata_treatment', 'Metadata_Pathway', 'Metadata_Plate', 'Metadata_Well']

,Metadata_WellRow,Metadata_WellCol,Metadata_heart_number,Metadata_cell_type,Metadata_heart_failure_type,Metadata_treatment,Metadata_Pathway,Metadata_Plate,Metadata_Well,Cytoplasm_AreaShape_Area,...,Nuclei_Texture_Variance_ER_3_02_256,Nuclei_Texture_Variance_ER_3_03_256,Nuclei_Texture_Variance_Mito_3_00_256,Nuclei_Texture_Variance_Mito_3_01_256,Nuclei_Texture_Variance_Mito_3_02_256,Nuclei_Texture_Variance_Mito_3_03_256,Nuclei_Texture_Variance_PM_3_00_256,Nuclei_Texture_Variance_PM_3_01_256,Nuclei_Texture_Variance_PM_3_02_256,Nuclei_Texture_Variance_PM_3_03_256
0,B,2,7,healthy,None,DMSO,None,CARD-CelIns-CX7_251201190001,B02,28725.0,...,4.622644,4.501794,4.676729,4.340622,4.840751,4.609525,1.224019,1.166119,1.184628,1.163209
1,B,3,25,failing,dilated_cardiomyopathy,UCD-0159266,Others,CARD-CelIns-CX7_251201190001,B03,34122.0,...,3.385785,3.271493,0.940637,0.922451,0.975107,0.921450,0.621384,0.605316,0.636911,0.611900