# Update Excel file into platemap CSV

In [1]:
import pathlib
import pandas as pd

## Load in excel spreadsheet as pandas dataframe

In [2]:
excel_df = pd.read_excel(pathlib.Path("/home/jenna/mnt/Way_McKinsey_Cardiac_Fibrosis/Compound_Screen/hit_validation_cell_painting/Hit Validation Platemap - Way Lab.xlsx"))

print(excel_df.shape)
excel_df.head()

(60, 7)

,WellRow,WellCol,well_position,heart_number,cell_type,heart_failure_type,treatment
0,B,2,B02,7,nonfailing,NaN,DMSO
1,B,3,B03,25,failing,dilated_cardiomyopathy,J0337
2,B,4,B04,25,failing,dilated_cardiomyopathy,J0899
3,B,5,B05,7,nonfailing,NaN,DMSO
4,B,6,B06,25,failing,dilated_cardiomyopathy,J0528

## Update well row and column names to match the format of other columns

In [3]:
# Rename WellCol and WellRow columns to match other columns
excel_df = excel_df.rename(columns={'WellCol': 'well_column', 'WellRow': 'well_row'})

# Check example to see if update occurred properly
print(excel_df.shape)
excel_df.head()

(60, 7)

,well_row,well_column,well_position,heart_number,cell_type,heart_failure_type,treatment
0,B,2,B02,7,nonfailing,NaN,DMSO
1,B,3,B03,25,failing,dilated_cardiomyopathy,J0337
2,B,4,B04,25,failing,dilated_cardiomyopathy,J0899
3,B,5,B05,7,nonfailing,NaN,DMSO
4,B,6,B06,25,failing,dilated_cardiomyopathy,J0528

## Fill NaN in heart failure type to "nonfailing"

In [4]:
# Fill NaN in heart_failure_type to "nonfailing"
excel_df['heart_failure_type'] = excel_df['heart_failure_type'].fillna('nonfailing')

# Check if columns have been properly updated
print(excel_df.shape)
excel_df.head()

(60, 7)

,well_row,well_column,well_position,heart_number,cell_type,heart_failure_type,treatment
0,B,2,B02,7,nonfailing,nonfailing,DMSO
1,B,3,B03,25,failing,dilated_cardiomyopathy,J0337
2,B,4,B04,25,failing,dilated_cardiomyopathy,J0899
3,B,5,B05,7,nonfailing,nonfailing,DMSO
4,B,6,B06,25,failing,dilated_cardiomyopathy,J0528

## Save as a CSV file

In [5]:
# make platemap output dir
output_dir = pathlib.Path("./platemaps")
output_dir.mkdir(exist_ok=True)

# Generate new CSV for platemap
platemap_csv_path = output_dir / "platemap_validation.csv"
excel_df.to_csv(platemap_csv_path, index=False)